<?php
function mt_event_badge_print_preprocess_page(&$variables){
  // Check if the page is the view page for badge print.
  // if (\Drupal::routeMatch()->getRouteName() !== 'view.mt_badges.page_1') {
  //   return;
  // }
  $route_name = \Drupal::routeMatch()->getRouteName();
  $needle = 'view.mt_badges';

  if (!str_starts_with($route_name, $needle)) {
    return;
  }

  foreach (\Drupal::theme()
             ->getActiveTheme()
             ->getRegions() as $region) {
    if (isset($variables['page'][$region]) && $region !== 'content') {
      unset($variables['page'][$region]);
    }
  }

  $variables['#attached']['library'][] = 'mt_event_badge_print/mt_event_badge_print';
}
