version: '3'

services:
  mysql:
    image: percona/percona-server:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#     volumes:
#       - mysql:/var/lib/mysql
#    ports:
#      - 3306:3306
