version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
#     ports:
#       - '8080:8080'
#       - '8443:8443'


  mysql:
    image: percona/percona-server:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#    volumes:
#      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
